### ISSUE TITLE
Engine name

### ISSUE THREAD

**Issue by SzotsGabor** [spamdrew128/Wahoo#33]
Hi Andrew,

Yes, I know I could rename them but I'd still like version number to appear in the engine name as well.

BTW, is this a Rust version of Apotheosis? Is the Apotheosis branch abandoned?

Gabor Szots
CCRL testing group

**Comment by spamdrew128** [comment]
I can include the name in future release executables. This is not a version of Apotheosis, this is a completely new engine that is not affiliated with Apotheosis in any way besides authorship, and should be treated as such. Apotheosis may receive small patches in the future, but most of my focus will be spent on Wahoo for the foreseeable future.

Sorry for the late response. I somehow did not see this issue.
